### ISSUE TITLE
Cuda Version out of Sync with Tensorflow

### ISSUE THREAD

**Issue by AlessandroFasse** [ITISFoundation/jupyter-machine-learning#4]
Currently we have Cuda `11.0` including cudNN `8.0` is installed. However, for tensorflow `2.9.X` we need to have `11.2` and `8.1` as shown on this page

https://www.tensorflow.org/install/source#gpu

**Comment by elisabettai** [comment]
Thanks for reporting this. Could also please post the error you're getting (and the code that generated that), so that we can keep track?

**Comment by elisabettai** [comment]
Solved by #5 (we released a new version of the service, 2.0.2)
